subject177 = {
    "data": [
        {
            "charcID": 4,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Вид застежки",
            "required": false,
            "unitName": "",
            "maxCount": 2,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 6,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Вырез горловины",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 10,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Тип рукава",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 11,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Покрой",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 12,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Рисунок",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 13,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Фактура материала",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 48,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Тип карманов",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 50,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Декоративные элементы",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 51,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Любимые герои",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 1010,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Утеплитель",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 1015,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Материал подкладки",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 6153,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Тип посадки",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 11892,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Уход за вещами",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 18769,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Сезон",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 23771,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Особенности модели",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 23796,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Назначение",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 54337,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Размер",
            "required": false,
            "unitName": "",
            "maxCount": 0,
            "popular": false,
            "charcType": 0
        },
        {
            "charcID": 56827,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Опции капюшона",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 57021,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Модель юбки",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 57556,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Модель костюма",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 85580,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Модель брюк",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 88815,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Температурный режим",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 89025,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Характеристика пух/перо (fill power)",
            "required": false,
            "unitName": "куб. дюйм на унцию",
            "maxCount": 0,
            "popular": false,
            "charcType": 4
        },
        {
            "charcID": 89030,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Плотность синтетического утеплителя",
            "required": false,
            "unitName": "г/кв.м",
            "maxCount": 0,
            "popular": false,
            "charcType": 4
        },
        {
            "charcID": 165482,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Рост модели на фото",
            "required": false,
            "unitName": "см",
            "maxCount": 0,
            "popular": false,
            "charcType": 4
        },
        {
            "charcID": 165505,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Параметры модели на фото (ОГ-ОТ-ОБ)",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 204557,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Пол",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 213929,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Тип ростовки",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 246961,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Размер на модели",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 378533,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Комплектация",
            "required": false,
            "unitName": "",
            "maxCount": 12,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 7488315,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Коллекция",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 14177449,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Цвет",
            "required": false,
            "unitName": "",
            "maxCount": 5,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 14177450,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Состав",
            "required": false,
            "unitName": "",
            "maxCount": 20,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 14177451,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Страна производства",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 14177453,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "SKU",
            "required": false,
            "unitName": "",
            "maxCount": 0,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 14177456,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Рос. размер",
            "required": false,
            "unitName": "",
            "maxCount": 0,
            "popular": false,
            "charcType": 0
        },
        {
            "charcID": 15000001,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "ТНВЭД",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001135,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Номер декларации соответствия",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001136,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Номер сертификата соответствия",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001137,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Дата регистрации сертификата/декларации",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001138,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Дата окончания действия сертификата/декларации",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001405,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Ставка НДС",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001650,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "ИКПУ",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15001706,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Код упаковки",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        },
        {
            "charcID": 15002997,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Тип низа",
            "required": false,
            "unitName": "",
            "maxCount": 2,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 15002998,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Тип верха",
            "required": false,
            "unitName": "",
            "maxCount": 3,
            "popular": true,
            "charcType": 1
        },
        {
            "charcID": 15003293,
            "subjectName": "Костюмы",
            "subjectID": 177,
            "name": "Артикул OZON",
            "required": false,
            "unitName": "",
            "maxCount": 1,
            "popular": false,
            "charcType": 1
        }
    ],
    "error": false,
    "errorText": "",
    "additionalErrors": null
}

