from prompts.generator import GENERATOR_SYSTEM_PROMPT
from prompts.validator import VALIDATOR_SYSTEM_PROMPT
from prompts.refiner import REFINER_SYSTEM_PROMPT
from prompts.color_detector import COLOR_DETECTOR_PROMPT
from prompts.description import (
    DESCRIPTION_SYSTEM_PROMPT,
    DESCRIPTION_VALIDATOR_SYSTEM_PROMPT,
    DESCRIPTION_REFINER_SYSTEM_PROMPT,
)
from prompts.title import (
    TITLE_SYSTEM_PROMPT,
    TITLE_VALIDATOR_SYSTEM_PROMPT,
    TITLE_REFINER_SYSTEM_PROMPT,
)

__all__ = [
    "GENERATOR_SYSTEM_PROMPT",
    "VALIDATOR_SYSTEM_PROMPT",
    "REFINER_SYSTEM_PROMPT",
    "COLOR_DETECTOR_PROMPT",
    "DESCRIPTION_SYSTEM_PROMPT",
    "DESCRIPTION_VALIDATOR_SYSTEM_PROMPT",
    "DESCRIPTION_REFINER_SYSTEM_PROMPT",
    "TITLE_SYSTEM_PROMPT",
    "TITLE_VALIDATOR_SYSTEM_PROMPT",
    "TITLE_REFINER_SYSTEM_PROMPT",
]