"""news

Revision ID: 238b636be88e
Revises: 9a6b3073a36d
Create Date: 2025-11-28 15:53:30.906081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238b636be88e'
down_revision: Union[str, Sequence[str], None] = '9a6b3073a36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'prompt_versions', 'prompt_templates', ['prompt_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    # ### end Alembic commands ###
