"""news

Revision ID: 28018bb9a885
Revises: 238b636be88e
Create Date: 2025-12-06 13:50:03.001065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28018bb9a885'
down_revision: Union[str, Sequence[str], None] = '238b636be88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('old_title', sa.Text(), nullable=True),
    sa.Column('new_title', sa.Text(), nullable=True),
    sa.Column('old_description', sa.Text(), nullable=True),
    sa.Column('new_description', sa.Text(), nullable=True),
    sa.Column('old_characteristics', sa.JSON(), nullable=True),
    sa.Column('new_characteristics', sa.JSON(), nullable=True),
    sa.Column('validation_score', sa.Integer(), nullable=True),
    sa.Column('title_score', sa.Integer(), nullable=True),
    sa.Column('description_score', sa.Integer(), nullable=True),
    sa.Column('iterations_done', sa.Integer(), nullable=True),
    sa.Column('best_iteration', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detected_colors', sa.JSON(), nullable=True),
    sa.Column('fixed_data', sa.JSON(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_history_article'), 'processing_history', ['article'], unique=False)
    op.create_index(op.f('ix_processing_history_created_at'), 'processing_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_history_id'), 'processing_history', ['id'], unique=False)
    op.create_index(op.f('ix_processing_history_nm_id'), 'processing_history', ['nm_id'], unique=False)
    op.create_index(op.f('ix_processing_history_user_id'), 'processing_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_history_user_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_nm_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_created_at'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_article'), table_name='processing_history')
    op.drop_table('processing_history')
    # ### end Alembic commands ###
