"""fixedall

Revision ID: 9a6b3073a36d
Revises: f688bde10652
Create Date: 2025-11-25 21:49:20.465871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a6b3073a36d'
down_revision: Union[str, Sequence[str], None] = 'f688bde10652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_history_article'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_created_at'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_nm_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_user_id'), table_name='processing_history')
    op.drop_table('processing_history')
    op.add_column('prompt_templates', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prompt_templates_created_by_id'), 'prompt_templates', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'prompt_templates', 'users', ['created_by_id'], ['id'])
    op.drop_column('prompt_templates', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prompt_templates', type_='foreignkey')
    op.drop_index(op.f('ix_prompt_templates_created_by_id'), table_name='prompt_templates')
    op.drop_column('prompt_templates', 'created_by_id')
    op.create_table('processing_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('old_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('old_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('old_characteristics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_characteristics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validation_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iterations_done', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('best_iteration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_colors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fixed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('photo_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('processing_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_history_pkey'))
    )
    op.create_index(op.f('ix_processing_history_user_id'), 'processing_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_processing_history_nm_id'), 'processing_history', ['nm_id'], unique=False)
    op.create_index(op.f('ix_processing_history_id'), 'processing_history', ['id'], unique=False)
    op.create_index(op.f('ix_processing_history_created_at'), 'processing_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_history_article'), 'processing_history', ['article'], unique=False)
    # ### end Alembic commands ###
